# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mdz1UO1M-KVfC9XH3V2n2twkZ5Ow8PkW
"""

import streamlit as st
import numpy as np
import pickle

# Load model
with open("best_model.pkl", "rb") as f:
    model = pickle.load(f)

st.set_page_config(page_title="Prediksi Dropout Mahasiswa", layout="centered")
st.title("🎓 Prediksi Dropout Mahasiswa – Jaya Jaya Institut")
st.write("Isi data di bawah untuk memprediksi apakah mahasiswa akan dropout atau tidak. Semua nilai sudah berupa angka sesuai hasil preprocessing.")

# Informasi Keterangan Nilai Kategorikal
with st.sidebar.expander("ℹ️ Keterangan Nilai Kategorikal"):
    st.markdown("""
**Marital_status**
1: Single
2: Married
3: Widower
4: Divorced
5: Facto Union
6: Legally Separated

**Application_mode** (Contoh)
1: 1st phase - general
15: International student
42: Transfer
(dll)

**Daytime_evening_attendance**
1: Daytime
0: Evening

**Previous_qualification**
1: Secondary education
2: Bachelor's degree
4: Master's
5: Doctorate
19: Basic education
(dll)

**Displaced / Debtor / Scholarship_holder / International**
1: Ya
0: Tidak

**Mothers_qualification / Fathers_qualification**
1: Secondary Edu
5: Doctorate
34: Unknown
(dll)

**Mothers_occupation / Fathers_occupation**
0: Student
1: Eksekutif
2: Profesi Ilmiah
...
194: Meal Preparation Assistants

**Admission_grade & Previous_qualification_grade**
Skala nilai: 0 – 200

**Curricular Units**
Mata kuliah semesteran:
- `enrolled`: jumlah diambil
- `evaluations`: jumlah dievaluasi
- `approved`: jumlah lulus
- `grade`: nilai rata-rata
- `without_evaluations`: tidak ikut ujian
    """)

# Daftar fitur input
feature_info = {
    "Marital_status": "Status pernikahan (1=single, 2=married, dst)",
    "Application_mode": "Metode pendaftaran (angka kategori)",
    "Application_order": "Urutan pilihan pendaftaran (0–9)",
    "Daytime_evening_attendance": "1=Daytime, 0=Evening",
    "Previous_qualification": "Kualifikasi pendidikan sebelumnya (kode numerik)",
    "Previous_qualification_grade": "Nilai dari pendidikan sebelumnya (0–200)",
    "Mothers_qualification": "Pendidikan ibu (kode numerik)",
    "Admission_grade": "Nilai ujian masuk (0–200)",
    "Displaced": "1=Ya, 0=Tidak",
    "Debtor": "1=Ya, 0=Tidak",
    "Tuition_fees_up_to_date": "1=Lunas, 0=Belum",
    "Gender": "1=Laki-laki, 0=Perempuan",
    "Scholarship_holder": "1=Ya, 0=Tidak",
    "Age_at_enrollment": "Usia saat mendaftar",
    "Curricular_units_1st_sem_enrolled": "Jumlah mata kuliah semester 1",
    "Curricular_units_1st_sem_evaluations": "Evaluasi semester 1",
    "Curricular_units_1st_sem_approved": "Mata kuliah disetujui semester 1",
    "Curricular_units_1st_sem_grade": "Rata-rata nilai semester 1 (0–20)",
    "Curricular_units_1st_sem_without_evaluations": "Mata kuliah tanpa evaluasi S1",
    "Curricular_units_2nd_sem_enrolled": "Jumlah mata kuliah semester 2",
    "Curricular_units_2nd_sem_evaluations": "Evaluasi semester 2",
    "Curricular_units_2nd_sem_approved": "Mata kuliah disetujui semester 2",
    "Curricular_units_2nd_sem_grade": "Rata-rata nilai semester 2 (0–20)",
    "Curricular_units_2nd_sem_without_evaluations": "Mata kuliah tanpa evaluasi S2"
}

user_input = []

st.subheader("📝 Formulir Input")
for feature, desc in feature_info.items():
    val = st.number_input(f"{feature}", help=desc)
    user_input.append(val)

if st.button("🔍 Prediksi"):
    input_data = np.array(user_input).reshape(1, -1)
    prediction = model.predict(input_data)[0]
    probability = model.predict_proba(input_data)[0][1]  # Probabilitas dropout

    st.subheader("📊 Hasil Prediksi")
    if prediction == 1:
        st.error(f"⚠️ Mahasiswa diprediksi akan **DROP OUT**.\n\nProbabilitas dropout: {probability:.2%}")
    else:
        st.success(f"✅ Mahasiswa diprediksi akan **LULUS**.\n\nProbabilitas dropout: {probability:.2%}")

st.markdown("---")
st.caption("Prototype oleh Data Scientist Jaya Jaya Institut | Streamlit App")